import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				className={`${inter.className} min-h-screen  flex justify-center items-center`}
			>
				<div className="max-w-[544px] w-full ">{children}</div>
			</body>
		</html>
	);
}
