export const contents = [
	{
		trivia: true,
		audio: "",
		name: "list",
		w: 12,
		x: 5,
		y: 3,
		img: "/demo/other/list.png",
	},
	{
		trivia: false,
		audio: "",
		name: "music",
		w: 32.5,
		x: 37.5,
		y: 47.36,
		img: "/demo/base/speaker.png",
		detail: "Novo Amor - Anchor",
	},
	{
		trivia: false,
		audio: "",
		name: "laptop",
		w: 30,
		x: 33.1,
		y: 43.7,
		img: "/demo/base/laptop.png",
		detail: "Wish",
	},
	{
		trivia: false,
		audio: "",
		name: "camera",
		w: 36,
		x: 58.8,
		y: 72.3,
		img: "/demo/base/camera.png",
		detail: "Wedding Photo",
		contents: [
			{
				img: "/demo/base/camera.png",
				alt: "Wedding Photo",
			},
			{
				img: "/demo/base/laptop.png",
				alt: "Wedding Photo",
			},
			{
				img: "/demo/base/amplop.png",
				alt: "Wedding Photo",
			},
		],
	},
	{
		trivia: false,
		audio: "",
		name: "amplop",
		w: 45,
		x: 26.8,
		y: 67.2,
		img: "/demo/base/amplop.png",
		detail: "Yo & Mi",
	},
	{
		trivia: false,
		audio: "",
		name: "date",
		w: 8,
		x: 65.7,
		y: 38.2,
		img: "/demo/base/date.png",
		detail: "31 Februari 2025",
		contents: "31 Februari 2025, 09:00 WIB",
	},
	{
		trivia: false,
		audio: "",
		name: "globe",
		w: 21.5,
		x: 78.5,
		y: 45.8,
		img: "/demo/base/globe.png",
		detail: "Ndalem Hanoman",
	},
	{
		trivia: false,
		audio: "",
		name: "bottle",
		w: 33.4,
		x: 65.5,
		y: 64.2,
		img: "/demo/base/bottle.png",
		detail: "Wedding Invitation",
		contents:
			"Hello Yomies! \n\nThis is a wedding invitation that provides a unique experience for guests. Instead of simply displaying wedding details directly, this invitation encourages guests to interact with various image objects scattered throughout the invitation page. \n\n✨Each object plays a special role in conveying wedding details and trivia. \n\n🎉Enjoy the experience and see you at the wedding! \n\nBest regards,\nYomify🐾",
	},
];
