export const contents = [
	{
		trivia: true,
		audio: "",
		name: "list",
		w: 12,
		x: 10,
		y: 7,
		img: "/demo/base/list.png",
	},
	{
		trivia: true,
		audio: "",
		name: "hint",
		w: 12,
		x: 26,
		y: 7,
		img: "/demo/base/hint.png",
	},
	{
		trivia: true,
		audio: "",
		name: "music",
		w: 32.5,
		x: 53.6,
		y: 50.8,
		img: "/demo/base/speaker.png",
		detail: "Novo Amor - Anchor",
	},
	{
		trivia: false,
		audio: "",
		name: "laptop",
		w: 30,
		x: 48.1,
		y: 49.7,
		img: "/demo/base/laptop.png",
		detail: "Wish",
	},
	{
		trivia: false,
		audio: "",
		name: "camera",
		w: 36,
		x: 76.9,
		y: 82,
		img: "/demo/base/camera.png",
		detail: "Wedding Photo",
		contents: [
			{
				img: "/demo/base/camera.png",
				alt: "Wedding Photo",
			},
			{
				img: "/demo/base/laptop.png",
				alt: "Wedding Photo",
			},
			{
				img: "/demo/base/amplop.png",
				alt: "Wedding Photo",
			},
		],
	},

	{
		trivia: false,
		audio: "",
		name: "date",
		w: 8,
		x: 69.6,
		y: 40,
		img: "/demo/base/date.png",
		detail: "31 Februari 2025",
		contents: "31 Februari 2025, 09:00 WIB",
	},
	{
		trivia: false,
		audio: "",
		name: "map",
		w: 21.5,
		x: 89.3,
		y: 54.8,
		img: "/demo/base/map.png",
		detail: "Ndalem Hanoman",
	},
	{
		trivia: false,
		audio: "",
		name: "bottle",
		w: 33.4,
		x: 82,
		y: 68.9,
		img: "/demo/base/bottle.png",
		detail: "Wedding Invitation",
		contents:
			"Hello Yomies! \n\nThis is a wedding invitation that provides a unique experience for guests. Instead of simply displaying wedding details directly, this invitation encourages guests to interact with various image objects scattered throughout the invitation page. \n\n✨Each object plays a special role in conveying wedding details and trivia. \n\n🎉Enjoy the experience and see you at the wedding! \n\nBest regards,\nYomify🐾",
	},

	{
		trivia: true,
		audio: "",
		name: "outfit",
		w: 47.8,
		x: 35.2,
		y: 87.4,
		img: "/demo/base/outfit.png",
	},
	{
		trivia: false,
		audio: "",
		name: "amplop",
		w: 45,
		x: 50,
		y: 71.8,
		img: "/demo/base/amplop.png",
		detail: "Romeo & Juliet",
	},
];
